###
# Configurações básicas e QOL
###
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

# Muda o prefix
unbind C-b
set -g prefix C-" "
bind-key C-" " send-prefix

# Reload do arquivo de conf
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Movimentação estilo vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Alt+hjkl para trocar os paineis - estilo Vim
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Alt+number para selecionar as windows
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Troca de windows com Shift+seta-direcional (<- ou ->)
bind -n S-Left previous-window
bind -n S-Right next-window

# Divide a tela entre vertical (v) e baixo (b)
bind b split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# Inicia a contagem dos paineis e janelas em 1 ao inves de 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Copia e cola como Vim - desabilita o scroll do mouse
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

###
# CONFIGURAÇÕES DE ESTILOS
###

# Gruvbox-dark
gruv_bg="#504945" #gruv-bg2
gruv_fg="#ebdbb2" #gruv-fg
gruv_cyan="#83a598" #grub-blue12
gruv_black="#1d2021" #gruv-bg0_h
gruv_gray="#928374" #gruv-gray8
gruv_magenta="#d3869b" #gruv-pyrple13
gruv_red="#fb4934" #gruv-red9
gruv_green="#689d6a" #gruv-aqua6
gruv_yellow="#d79921" #gruv-yellow3
gruv_blue="#458588" #grub-blue4
gruv_orange="#fe8019" #gruv-orange

# Status bar
set -g status "on"
set -g status-position top
set -g status-bg "${gruv_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# Status leftset -g status-left
set -g status-left "#[fg=$gruv_orange] #S | "

# Status right
set -g status-right "#[fg=$gruv_orange] %F | %H:%M | #H "

# Messages
set -g message-style "fg=${gruv_black},bg=${gruv_red},align=centre"
set -g message-command-style "fg=${gruv_cyan},bg=${gruv_gray},align=centre"

# Panes
set -g pane-border-style "fg=${gruv_gray}"
set -g pane-active-border-style "fg=${gruv_blue}"
set -g pane-border-lines simple

# Windows
set -g window-status-separator "#[fg=$gruv_orange] || "
set -g window-status-style "fg=${gruv_fg},bg=${gruv_bg},none"

set -g window-status-current-format "#I: #W (#F)"
set -g window-status-format "#I: #W #F"
# set -g window-status-current-style "" configura o estilo da janela ativa


###
# PLUGINS
###

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'alexwforsythe/tmux-which-key'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
